In [3]:
import pandas as pd

In [17]:
distancias_entre_pilares = pd.read_table('distancias.txt', sep=',')

distancias_entre_pilares

    Pilar  Dist_x  Dist_y
0       1   20.35    0.10
1       2   16.30    0.10
2       3    7.28    0.10
3       4    2.85    0.30
4       5   20.55    3.50
5       6   16.35    3.30
6       7   13.95    3.50
7       8   11.15    3.40
8       9    9.45    3.40
9      10    6.95    3.30
10     11    2.85    3.30
11     12   12.55    4.80
12     13   11.15    5.00
13     14    9.45    5.00
14     15   22.30    8.50
15     16   17.30    9.90
16     17   13.85    8.50
17     18   11.70    8.70
18     19    9.45    8.28
19     20    6.10    9.90
20     21    0.90    8.69
21     22   22.30   11.55
22     23    1.30   11.35
23     24   22.30   14.50
24     25   17.30   14.50
25     26   11.70   13.30
26     27    6.10   14.50
27     28    1.10   14.50

In [20]:
#dados.to_csv('./aluguel.csv/./aluguel_residencial.csv',sep=';', index = False)

In [22]:
distancias_entre_pilares.to_csv('./distancias.csv', sep=',', index = False)